import{a as v,S as b,N as c,i as M}from"./assets/vendor-COPdusF7.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function f(i,a=1,n=40){const r="https://pixabay.com/api/",e="48018775-66f870a0a55ddc658d7ca6c06",o=new URLSearchParams({key:e,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:n});console.log("Запит до API:",`${r}?${o}`);try{const s=await v.get(`${r}?${o}`);return console.log("Успішна відповідь від API:",s.data),s}catch(s){throw console.error("Помилка у запиті API:",s),s}}const t={galleryDiv:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),form:document.querySelector(".search-form"),input:document.querySelector('.search-form input[name="searchQuery"]')};t.galleryDiv||console.error("Gallery not found in DOM");t.loadMoreBtn||console.error("Load More button not found in DOM");t.form||console.error("Form not found in DOM");t.input||console.error("Input field not found in DOM");function D(){t.galleryDiv.innerHTML=""}function p(i){const a=E(i),n=document.createElement("div");n.innerHTML=a,n.classList.add("hidden"),t.galleryDiv.appendChild(n);const r=n.querySelectorAll("img");let e=0;r.forEach(o=>{o.addEventListener("load",()=>{e+=1,e===r.length&&n.classList.remove("hidden")}),o.addEventListener("error",()=>{console.error("Error loading image:",o.src)})})}function E(i){return i.map(({webformatURL:a,largeImageURL:n,tags:r,likes:e,views:o,comments:s,downloads:L})=>`
        <div class="photo-card">
          <a href="${n}" class="gallery-image">
            <img src="${a}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes: ${e}</b></p>
            <p class="info-item"><b>Views: ${o}</b></p>
            <p class="info-item"><b>Comments: ${s}</b></p>
            <p class="info-item"><b>Downloads: ${L}</b></p>
          </div>
        </div>
      `).join("")}let l=1;const u=40,m=document.getElementById("loading-indicator"),y=()=>m.style.display="block",h=()=>m.style.display="none",d=()=>{var i;return(i=t==null?void 0:t.loadMoreBtn)==null?void 0:i.classList.add("load-more-hidden")},N=()=>{var i;return(i=t==null?void 0:t.loadMoreBtn)==null?void 0:i.classList.remove("load-more-hidden")};d();const g=new b(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:200});document.addEventListener("DOMContentLoaded",()=>{c.Notify.init({position:"right-bottom",clickToClose:!0,timeout:3e3})});async function P(i){var n,r;i.preventDefault();const a=t.input.value.trim();if(!a){d(),c.Notify.failure("Please enter a search query.");return}l=1,D(),y();try{const e=await f(a,l,u);if(!((r=(n=e==null?void 0:e.data)==null?void 0:n.hits)!=null&&r.length)){M.error({title:"Error",message:"No images found."});return}const o=e.data.totalHits;o>u?N():d(),c.Notify.success(`Success! Found ${o} images.`),p(e.data.hits),g.refresh()}catch{c.Notify.failure("An error occurred. Please try again.")}finally{h()}}async function S(){var a,n;l+=1;const i=t.input.value.trim();y();try{const r=await f(i,l,u);if(!((n=(a=r==null?void 0:r.data)==null?void 0:a.hits)!=null&&n.length)){d(),c.Notify.failure("No more results.");return}p(r.data.hits),g.refresh()}catch{c.Notify.failure("An error occurred while loading more images.")}finally{h()}}t!=null&&t.form&&t.form.addEventListener("submit",P);t!=null&&t.loadMoreBtn&&t.loadMoreBtn.addEventListener("click",S);
//# sourceMappingURL=index.js.map
