import{a as b,S as M,N as c,i as v}from"./assets/vendor-COPdusF7.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function m(n,i=1,a=40){const r="https://pixabay.com/api/",e="48018775-66f870a0a55ddc658d7ca6c06",o=new URLSearchParams({key:e,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:a});console.log("Запит до API:",`${r}?${o}`);try{const s=await b.get(`${r}?${o}`);return console.log("Успішна відповідь від API:",s.data),s}catch(s){throw console.error("Помилка у запиті API:",s),s}}const t={galleryDiv:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),form:document.querySelector(".search-form"),input:document.querySelector('.search-form input[name="searchQuery"]')};t.galleryDiv||console.error("Gallery not found in DOM");t.loadMoreBtn||console.error("Load More button not found in DOM");t.form||console.error("Form not found in DOM");t.input||console.error("Input field not found in DOM");function P(){t.galleryDiv.innerHTML=""}function p(n){const i=w(n),a=document.createElement("div");a.innerHTML=i;const e=Array.from(a.querySelectorAll("img")).map(o=>new Promise((s,u)=>{o.onload=()=>s(o),o.onerror=()=>u(`Failed to load image: ${o.src}`)}));Promise.all(e).then(()=>{t.galleryDiv.insertAdjacentHTML("beforeend",i)}).catch(o=>console.error(o))}function w(n){return n.map(({webformatURL:i,largeImageURL:a,tags:r,likes:e,views:o,comments:s,downloads:u})=>`
        <div class="photo-card">
          <a href="${a}" class="gallery-image">
            <img src="${i}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes: ${e}</b></p>
            <p class="info-item"><b>Views: ${o}</b></p>
            <p class="info-item"><b>Comments: ${s}</b></p>
            <p class="info-item"><b>Downloads: ${u}</b></p>
          </div>
        </div>
      `).join("")}let l=1;const f=40,y=document.getElementById("loading-indicator"),h=()=>y.style.display="block",g=()=>y.style.display="none",d=()=>{var n;return(n=t==null?void 0:t.loadMoreBtn)==null?void 0:n.classList.add("load-more-hidden")},D=()=>{var n;return(n=t==null?void 0:t.loadMoreBtn)==null?void 0:n.classList.remove("load-more-hidden")};d();const L=new M(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:200});document.addEventListener("DOMContentLoaded",()=>{c.Notify.init({position:"right-bottom",clickToClose:!0,timeout:3e3})});async function N(n){var a,r;n.preventDefault();const i=t.input.value.trim();if(!i){d(),c.Notify.failure("Please enter a search query.");return}l=1,P(),h();try{const e=await m(i,l,f);if(!((r=(a=e==null?void 0:e.data)==null?void 0:a.hits)!=null&&r.length)){v.error({title:"Error",message:"No images found."});return}const o=e.data.totalHits;o>f?D():d(),c.Notify.success(`Success! Found ${o} images.`),p(e.data.hits),L.refresh()}catch{c.Notify.failure("An error occurred. Please try again.")}finally{g()}}async function S(){var i,a;l+=1;const n=t.input.value.trim();h();try{const r=await m(n,l,f);if(!((a=(i=r==null?void 0:r.data)==null?void 0:i.hits)!=null&&a.length)){d(),c.Notify.failure("No more results.");return}p(r.data.hits),L.refresh()}catch{c.Notify.failure("An error occurred while loading more images.")}finally{g()}}t!=null&&t.form&&t.form.addEventListener("submit",N);t!=null&&t.loadMoreBtn&&t.loadMoreBtn.addEventListener("click",S);
//# sourceMappingURL=index.js.map
