import{a as M,S as N,N as i,i as b}from"./assets/vendor-COPdusF7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function u(t,n=1,a=40){const s="https://pixabay.com/api/",e="48018775-66f870a0a55ddc658d7ca6c06",r=new URLSearchParams({key:e,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:a});console.log("Запит до API:",`${s}?${r}`);try{const l=await M.get(`${s}?${r}`);return console.log("Успішна відповідь від API:",l.data),l}catch(l){throw console.error("Помилка у запиті API:",l),l}}const o={galleryDiv:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more"),form:document.querySelector(".search-form"),input:document.querySelector('.search-form input[name="searchQuery"]')};o.galleryDiv||console.error("Галерея не знайдена в DOM");o.loadMoreBtn||console.error("Кнопка 'Load More' не знайдена в DOM");o.form||console.error("Форма не знайдена в DOM");o.input||console.error("Поле введення не знайдено в DOM");function L(){o.galleryDiv.innerHTML=""}function p(t){o.galleryDiv.insertAdjacentHTML("beforeend",v(t))}function v(t){return t.map(({webformatURL:n,largeImageURL:a,tags:s,likes:e,views:r,comments:l,downloads:h})=>`
        <div class="photo-card">
          <a href="${a}" class="gallery-image">
            <img src="${n}" alt="${s}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes: ${e}</b></p>
            <p class="info-item"><b>Views: ${r}</b></p>
            <p class="info-item"><b>Comments: ${l}</b></p>
            <p class="info-item"><b>Downloads: ${h}</b></p>
          </div>
        </div>
      `).join("")}let c=1;const d=40,y=document.getElementById("loading-spinner"),B=()=>y.style.display="block",w=()=>y.style.display="none",f=()=>{o.loadMoreBtn?o.loadMoreBtn.style.display="none":console.warn("Елемент loadMoreBtn не знайдено.")},D=()=>{o.loadMoreBtn?o.loadMoreBtn.style.display="block":console.warn("Елемент loadMoreBtn не знайдено.")};f();const m=new N(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:200});document.addEventListener("DOMContentLoaded",()=>{typeof i>"u"?console.error("Notiflix не завантажено!"):(i.Notify.init({position:"right-bottom",clickToClose:!0,timeout:3e3}),console.log("Notiflix завантажено успішно!"))});async function $(t){var a,s;if(t.preventDefault(),console.log("Подія submit викликана."),!o||!o.input){console.error("Елемент input не знайдено у об'єкті elem."),i.Notify&&i.Notify.failure("Сталася помилка. Перевірте код.");return}const n=o.input.value.trim();if(console.log("Текст пошуку:",n),!n){f(),i.Notify&&i.Notify.failure("Будь ласка, введіть запит для пошуку.");return}c=1,L(),B();try{console.log("Відправляємо запит до API...");const e=await u(n,c,d);if(!((s=(a=e==null?void 0:e.data)==null?void 0:a.hits)!=null&&s.length)){b.error({title:"Помилка",message:"Зображення не знайдено."});return}const r=e.data.totalHits;console.log("Знайдено зображень:",r),r<=d?f():D(),i.Notify&&i.Notify.success(`Ура! Знайдено ${r} зображень.`),p(e.data.hits),m.refresh()}catch(e){g(e)}finally{w()}}async function P(){var n,a;if(console.log("Натиснута кнопка 'Load More'."),c+=1,!o||!o.input){console.error("Елемент input не знайдено у об'єкті elem."),i.Notify&&i.Notify.failure("Сталася помилка. Перевірте код.");return}const t=o.input.value.trim();console.log("Текст пошуку для додаткового завантаження:",t);try{const s=await u(t,c,d);if(!((a=(n=s==null?void 0:s.data)==null?void 0:n.hits)!=null&&a.length)){f(),i.Notify&&i.Notify.failure("Більше результатів немає.");return}p(s.data.hits),m.refresh()}catch(s){g(s)}}function g(t){var n;console.error("Помилка при виконанні запиту:",t),t.response?(console.error("Дані відповіді з помилкою:",t.response.data),i.Notify&&i.Notify.failure(`Помилка: ${((n=t.response.data)==null?void 0:n.message)||"Сервер не відповідає."}`)):t.message?(console.error("Технічна помилка:",t.message||t),i.Notify&&i.Notify.failure("Сталася помилка при з'єднанні з сервером.")):(console.error("Невідома помилка:",t),i.Notify&&i.Notify.failure("Невідома помилка."))}o!=null&&o.form?o.form.addEventListener("submit",$):console.error("Елемент form не знайдено у об'єкті elem.");o!=null&&o.loadMoreBtn?o.loadMoreBtn.addEventListener("click",P):console.error("Елемент loadMoreBtn не знайдено у об'єкті elem.");
//# sourceMappingURL=index.js.map
